### ISSUE TITLE
Add Packages

### ISSUE THREAD

**Issue by Marsychen** [stab-virtual-jabog32/fpt#126]
Make it possible to group flight into packages.
Properties of a package could be:
- Package Lead
- Package Freq
- AO
- Taskings
and whatever else comes to our minds

**Comment by DTomas15** [comment]
Initial draf published at Branch DTomas15/issue126
![image](https://github.com/user-attachments/assets/4d304b4d-2ade-46d1-bab2-84f13e57d2a6)

![image](https://github.com/user-attachments/assets/7f1037a2-11d8-4e93-bf81-72881d49335a)
Shows the Package Creation Mask
However, you must ensure that Lead Flight is also selected in Select Flights, otherwise the package will not be created

**Comment by DTomas15** [comment]
Release candidate 763737264c2cb585febd40c415103219da6ce5c9 pushed to [deploy-test](https://fpt-test.virtual-jabog32.de/)

**Comment by Marsychen** [comment]
Good first iteration, would be good to add Edit Package.
Also the Package information should be available on the kneeboard that will be generated, therefore we would also need to edit the MDC mod.

**Comment by DTomas15** [comment]
Closed by DTomas15/issue126
